#!/bin/zsh
aws s3api create-bucket \
  --acl public-read \
  --bucket parcels.painkillergis.com

aws s3api put-bucket-cors \
  --bucket parcels.painkillergis.com \
  --cors-configuration file://scripts/aws:s3/cors-configuration.json

aws s3api put-bucket-policy \
  --bucket parcels.painkillergis.com \
  --policy file://scripts/aws:s3/bucket-policy.json

aws s3api put-bucket-website \
  --bucket parcels.painkillergis.com \
  --website-configuration file://scripts/aws:s3/website-configuration.json
